name: CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: none
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint

  publish-dry-run:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: none
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm dlx pkg-pr-new publish --pnpm
