name: npm publish

on:
    push:
        branches:
            - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: none
    steps:
        - uses: actions/checkout@v4
        - uses: pnpm/action-setup@v4
          with:
            version: 10.6.4
        - run: pnpm install --frozen-lockfile
        - run: pnpm publish --no-git-checks --provenance --access public --tag latest
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}